"use client";

import { useMemo, useState, useTransition } from "react";
import { AlertTriangle, CheckCircle2, Search, Sparkles } from "lucide-react";
import { generarBorradorRutina } from "@/app/admin/generador/actions";
import { RutinaDraftEditor } from "@/components/admin/RutinaDraftEditor";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input, Select, Textarea } from "@/components/ui/Input";
import type { BriefGenerador, ObjetivoEntrenamiento, PrioridadBloque, Distribucion } from "@/lib/generador-rutinas/tipos";
import type { RutinaExtraida } from "@/lib/ai/extraerRutina";

type Alumno = { id: string; nombre: string; objetivo: string | null; perfilCompleto: boolean; requiereRevision: boolean; dias: number | null; minutos: number | null };
type Ejercicio = { id: string; nombre: string; grupo: string; equipo: string };

export function GeneradorRutinasPanel({ alumnos, ejercicios }: { alumnos: Alumno[]; ejercicios: Ejercicio[] }) {
  const [alumnoId, setAlumnoId] = useState(alumnos[0]?.id ?? "");
  const alumno = alumnos.find((a) => a.id === alumnoId);
  const [objetivo, setObjetivo] = useState<ObjetivoEntrenamiento>("hipertrofia");
  const [prioridad, setPrioridad] = useState<PrioridadBloque>("hipertrofia");
  const [dias, setDias] = useState(3); const [minutos, setMinutos] = useState(60); const [cantidad, setCantidad] = useState(7);
  const [distribucion, setDistribucion] = useState<Distribucion>("automatica");
  const [cardio, setCardio] = useState<BriefGenerador["cardio"]>("moderado"); const [cardioMinutos, setCardioMinutos] = useState(10);
  const [abdominales, setAbdominales] = useState(false); const [soloMaquinas, setSoloMaquinas] = useState(false); const [evitarSaltos, setEvitarSaltos] = useState(false);
  const [obligatorios, setObligatorios] = useState<string[]>([]); const [prohibidos, setProhibidos] = useState<string[]>([]); const [preferidos, setPreferidos] = useState<string[]>([]);
  const [observaciones, setObservaciones] = useState(""); const [busqueda, setBusqueda] = useState("");
  const [rutina, setRutina] = useState<RutinaExtraida | null>(null); const [alertas, setAlertas] = useState<string[]>([]); const [reglas, setReglas] = useState<string[]>([]); const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const visibles = useMemo(() => ejercicios.filter((e) => `${e.nombre} ${e.grupo} ${e.equipo}`.toLowerCase().includes(busqueda.toLowerCase())).slice(0, 30), [ejercicios, busqueda]);
  const alternar = (id: string, lista: string[], set: (v: string[]) => void) => set(lista.includes(id) ? lista.filter((x) => x !== id) : [...lista, id]);
  const elegirAlumno = (id: string) => { setAlumnoId(id); const a = alumnos.find((x) => x.id === id); if (a?.dias) setDias(a.dias); if (a?.minutos) setMinutos(a.minutos); };
  const generar = () => { setError(null); startTransition(async () => { const r = await generarBorradorRutina({ alumnoId, objetivo, prioridad, dias, minutosSesion: minutos, distribucion, ejerciciosPorSesion: cantidad, cardio, cardioMinutos, abdominales, soloMaquinas, evitarSaltos, obligatorios, prohibidos, preferidos, tecnicaNombre: null, observaciones }); if (!r.ok) return setError(r.error); setRutina(r.rutina); setAlertas(r.alertas); setReglas(r.reglas); }); };
  if (rutina) return <div className="space-y-3">{alertas.map((a) => <Card key={a} padding="p-3" className="border border-warning"><p className="text-caption flex gap-2"><AlertTriangle size={16} />{a}</p></Card>)}<Card padding="p-3"><p className="text-caption mb-2 font-semibold">Reglas aplicadas</p>{reglas.map((r) => <p key={r} className="text-caption flex gap-2 text-text-secondary"><CheckCircle2 size={14} className="text-success" />{r}</p>)}</Card><RutinaDraftEditor alumnoIds={[alumnoId]} draftInicial={rutina} onDescartar={() => setRutina(null)} /></div>;
  return <div className="space-y-4">
    <Card className="space-y-3"><div><label className="text-caption mb-1 block text-text-tertiary">ALUMNO</label><Select value={alumnoId} onChange={(e) => elegirAlumno(e.target.value)}>{alumnos.map((a) => <option key={a.id} value={a.id}>{a.nombre}{!a.perfilCompleto ? " · perfil pendiente" : a.requiereRevision ? " · revisar" : ""}</option>)}</Select></div>{alumno && !alumno.perfilCompleto && <p className="text-caption text-warning">El alumno aún no completó “Mi entrenamiento”. Puedes generar igualmente y definir los datos tú.</p>}{alumno?.requiereRevision && <p className="text-caption flex gap-2 text-warning"><AlertTriangle size={16} />Hay antecedentes de salud o molestias pendientes de revisión. El sistema no diagnostica ni reemplaza tu criterio.</p>}</Card>
    <Card className="space-y-3"><p className="text-caption text-text-tertiary">OBJETIVO Y ESTRUCTURA</p><Select value={objetivo} onChange={(e) => setObjetivo(e.target.value as ObjetivoEntrenamiento)}><option value="hipertrofia">Hipertrofia</option><option value="fuerza">Fuerza</option><option value="perdida_grasa">Pérdida de grasa</option><option value="recomposicion">Recomposición</option><option value="condicion_fisica">Condición física</option><option value="rendimiento">Rendimiento</option><option value="mantencion">Mantención</option></Select><Select value={prioridad} onChange={(e) => setPrioridad(e.target.value as PrioridadBloque)}><option value="hipertrofia">Prioridad hipertrofia</option><option value="fuerza">Prioridad fuerza</option><option value="cardio">Prioridad cardio</option><option value="tecnica">Prioridad técnica</option><option value="retorno">Retorno gradual</option><option value="adherencia">Adherencia/simpleza</option></Select><Select value={distribucion} onChange={(e) => setDistribucion(e.target.value as Distribucion)}><option value="automatica">Distribución automática</option><option value="full_body">Full body</option><option value="upper_lower">Upper / lower</option><option value="push_pull_legs">Push / pull / legs</option></Select><div className="grid grid-cols-3 gap-2"><Input aria-label="Días" type="number" min={1} max={7} value={dias} onChange={(e) => setDias(Number(e.target.value))} /><Input aria-label="Minutos" type="number" min={20} max={180} value={minutos} onChange={(e) => setMinutos(Number(e.target.value))} /><Input aria-label="Ejercicios" type="number" min={1} max={15} value={cantidad} onChange={(e) => setCantidad(Number(e.target.value))} /></div><p className="text-micro text-text-tertiary">Días · minutos · ejercicios por sesión</p></Card>
    <Card className="space-y-3"><p className="text-caption text-text-tertiary">CARDIO Y REGLAS VIP</p><div className="grid grid-cols-2 gap-2"><Select value={cardio} onChange={(e) => setCardio(e.target.value as BriefGenerador["cardio"])}><option value="ninguno">Sin cardio</option><option value="bajo">Cardio bajo</option><option value="moderado">Cardio moderado</option><option value="alto">Cardio alto</option></Select><Input type="number" min={0} max={90} value={cardioMinutos} onChange={(e) => setCardioMinutos(Number(e.target.value))} /></div>{[[abdominales,setAbdominales,"Agregar core al final"],[soloMaquinas,setSoloMaquinas,"Solo máquinas, poleas y Smith"],[evitarSaltos,setEvitarSaltos,"Excluir saltos e impacto alto"]].map(([v,s,t]) => <label key={String(t)} className="text-caption flex gap-2"><input type="checkbox" checked={v as boolean} onChange={(e) => (s as (x:boolean)=>void)(e.target.checked)} />{String(t)}</label>)}</Card>
    <Card className="space-y-3"><p className="text-caption text-text-tertiary">EJERCICIOS OBLIGATORIOS, PREFERIDOS Y PROHIBIDOS</p><div className="relative"><Search size={16} className="absolute left-3 top-3.5 text-text-tertiary" /><Input value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar por nombre, grupo o equipo" className="pl-9" /></div><div className="max-h-72 space-y-2 overflow-y-auto">{visibles.map((e) => <div key={e.id} className="radius-control border border-border p-2"><p className="text-caption font-medium">{e.nombre}</p><p className="text-micro text-text-tertiary">{e.grupo} · {e.equipo}</p><div className="mt-2 flex gap-1"><button type="button" onClick={() => alternar(e.id, obligatorios, setObligatorios)} className={`radius-control flex-1 py-1 text-micro ${obligatorios.includes(e.id) ? "bg-success text-black" : "bg-surface-2"}`}>Obligatorio</button><button type="button" onClick={() => alternar(e.id, preferidos, setPreferidos)} className={`radius-control flex-1 py-1 text-micro ${preferidos.includes(e.id) ? "bg-vip text-black" : "bg-surface-2"}`}>Preferido</button><button type="button" onClick={() => alternar(e.id, prohibidos, setProhibidos)} className={`radius-control flex-1 py-1 text-micro ${prohibidos.includes(e.id) ? "bg-error text-white" : "bg-surface-2"}`}>Prohibido</button></div></div>)}</div></Card>
    <Card><Textarea value={observaciones} onChange={(e) => setObservaciones(e.target.value)} placeholder="Observaciones del entrenador para este bloque" rows={3} /></Card>{error && <p className="text-caption text-error">{error}</p>}<Button onClick={generar} loading={pending} disabled={!alumnoId}><Sparkles size={18} />{pending ? "Aplicando reglas…" : "Generar borrador para revisar"}</Button>
  </div>;
}

