"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Check, Gift, PackageCheck, X } from "lucide-react";
import { ajustarStockRecompensaVip, cambiarEstadoRecompensaVip, guardarRecompensaVip, resolverCanjeVip } from "@/app/admin/puntos/recompensas-actions";
import type { CanjeVip, RecompensaVip } from "@/lib/recompensas/data";

export function RecompensasAdminPanel({ disponible, catalogo, canjes }: { disponible: boolean; catalogo: RecompensaVip[]; canjes: CanjeVip[] }) {
  const router = useRouter();
  const [mensaje, setMensaje] = useState<string | null>(null);
  const [procesando, iniciar] = useTransition();
  const ejecutar = (tarea: () => Promise<{ ok: boolean; error: string | null }>) => iniciar(async () => { const resultado = await tarea(); setMensaje(resultado.ok ? "Cambio guardado." : resultado.error); if (resultado.ok) router.refresh(); });
  if (!disponible) return <section className="rounded-2xl border border-warning/30 bg-warning/5 p-5"><Gift size={21} className="text-warning" /><h2 className="mt-2 text-sm font-bold text-text">Falta activar recompensas</h2><p className="mt-1 text-xs text-text-secondary">Ejecuta la migración 0107_recompensas_vip.sql en preview.</p></section>;
  return <section className="space-y-4 rounded-2xl border border-border bg-surface p-4">
    <div><h2 className="text-sm font-bold text-text">Catálogo y canjes</h2><p className="text-xs text-text-secondary">El stock se reserva y los puntos se descuentan en una sola transacción.</p></div>
    <form className="grid gap-2 md:grid-cols-5" onSubmit={(evento) => { evento.preventDefault(); const data = new FormData(evento.currentTarget); ejecutar(() => guardarRecompensaVip({ nombre: String(data.get("nombre") || ""), descripcion: String(data.get("descripcion") || ""), tipo: String(data.get("tipo") || "servicio") as "digital" | "servicio" | "fisica", costo: Number(data.get("costo")), stock: String(data.get("stock") || "").trim() ? Number(data.get("stock")) : null })); evento.currentTarget.reset(); }}>
      <input required name="nombre" placeholder="Nombre" className="rounded-xl border border-border bg-bg px-3 py-2 text-xs text-text" />
      <input name="descripcion" placeholder="Descripción" className="rounded-xl border border-border bg-bg px-3 py-2 text-xs text-text" />
      <select name="tipo" className="rounded-xl border border-border bg-bg px-3 py-2 text-xs text-text"><option value="servicio">Servicio</option><option value="digital">Digital</option><option value="fisica">Física</option></select>
      <div className="grid grid-cols-2 gap-2"><input required min="1" name="costo" type="number" placeholder="Puntos" className="min-w-0 rounded-xl border border-border bg-bg px-3 py-2 text-xs text-text" /><input min="0" name="stock" type="number" placeholder="Stock ∞" className="min-w-0 rounded-xl border border-border bg-bg px-3 py-2 text-xs text-text" /></div>
      <button disabled={procesando} className="rounded-xl bg-vip px-3 py-2 text-xs font-bold text-black">Crear recompensa</button>
    </form>
    {mensaje ? <p role="status" className="text-xs text-text-secondary">{mensaje}</p> : null}
    <div className="grid gap-2 md:grid-cols-2">{catalogo.map((item) => <article key={item.id} className="rounded-xl border border-border p-3"><div className="flex items-center gap-3"><Gift size={17} className="text-vip" /><div className="min-w-0 flex-1"><strong className="block truncate text-xs text-text">{item.nombre}</strong><small className="text-[10px] text-text-tertiary">{item.costoPuntos.toLocaleString("es-CL")} XP · {item.stock === null ? "stock continuo" : `${item.stock} unidades`}</small></div><button disabled={procesando} onClick={() => ejecutar(() => cambiarEstadoRecompensaVip(item.id, !item.activa))} className="rounded-lg border border-border px-2 py-1 text-[10px] text-text-secondary">{item.activa ? "Pausar" : "Activar"}</button></div><div className="mt-2 flex gap-1"><button disabled={procesando} onClick={() => ejecutar(() => ajustarStockRecompensaVip(item.id, -1))} className="rounded-lg border border-border px-2 py-1 text-[10px] text-text-secondary">−1</button><button disabled={procesando} onClick={() => ejecutar(() => ajustarStockRecompensaVip(item.id, 1))} className="rounded-lg border border-border px-2 py-1 text-[10px] text-text-secondary">+1</button><button disabled={procesando} onClick={() => ejecutar(() => ajustarStockRecompensaVip(item.id, 0, true))} className="rounded-lg border border-border px-2 py-1 text-[10px] text-text-secondary">Sin límite</button></div></article>)}</div>
    <div><h3 className="mb-2 text-xs font-bold text-text">Solicitudes</h3>{canjes.filter((canje) => canje.estado === "solicitado" || canje.estado === "aprobado").length ? <div className="space-y-2">{canjes.filter((canje) => canje.estado === "solicitado" || canje.estado === "aprobado").map((canje) => <article key={canje.id} className="rounded-xl border border-border p-3"><div className="flex items-center gap-3"><PackageCheck size={18} className="text-vip" /><div className="min-w-0 flex-1"><strong className="block text-xs text-text">{canje.alumnoNombre} · {canje.recompensaNombre}</strong><small className="text-[10px] text-text-tertiary">{canje.estado} · {canje.costo.toLocaleString("es-CL")} XP</small></div></div><div className="mt-3 flex flex-wrap gap-2">{canje.estado === "solicitado" ? <button onClick={() => ejecutar(() => resolverCanjeVip(canje.id, "aprobado", ""))} className="flex items-center gap-1 rounded-lg bg-success/15 px-3 py-2 text-[10px] font-bold text-success"><Check size={13} /> Aprobar</button> : <button onClick={() => ejecutar(() => resolverCanjeVip(canje.id, "entregado", ""))} className="flex items-center gap-1 rounded-lg bg-vip/15 px-3 py-2 text-[10px] font-bold text-vip"><PackageCheck size={13} /> Marcar entregado</button>}<button onClick={() => ejecutar(() => resolverCanjeVip(canje.id, "rechazado", "No fue posible completar la entrega."))} className="flex items-center gap-1 rounded-lg bg-error/10 px-3 py-2 text-[10px] font-bold text-error"><X size={13} /> Rechazar y reintegrar</button></div></article>)}</div> : <p className="text-xs text-text-tertiary">No hay canjes pendientes.</p>}</div>
  </section>;
}
